{% set name = "python-engineio" %}
{% set version = "4.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "9f34afa4170f5ba6e3d9ff158752ccf8fbb2145f16554b2f0fc84646675be99a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six >=1.9.0

test:
  imports:
    - engineio
    # - engineio.async_eventlet
    # - engineio.async_gevent
    # - engineio.async_gevent_uwsgi
    # - engineio.async_threading
    - engineio.middleware
    - engineio.packet
    - engineio.payload
    - engineio.server
    - engineio.socket

about:
  home: https://github.com/miguelgrinberg/python-engineio/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Engine.IO server'
  doc_url: https://python-engineio.readthedocs.io
  dev_url: https://github.com/miguelgrinberg/python-engineio/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ReimarBauer
