{% set name = "python-engineio" %}
{% set version = "4.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/miguelgrinberg/python-engineio/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7375254e85cef1e78559f4ed01f7cfba85a30d0a34d3695f0d96e5e9e73de92d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - wheel
  run:
    - python
    - simple-websocket >=0.10.0
  run_constrained:
    - requests >=2.21.0
    - websocket-client >=0.54.0
    - aiohttp >=3.4

# > raise RuntimeError("Event loop stopped before Future completed.")
# E RuntimeError: Event loop stopped before Future completed.
{% set skip_tests = "TestAsyncServer or TestSocket" %}

test:
  source_files:
    - tests
  imports:
    - engineio
    - engineio.middleware
    - engineio.packet
    - engineio.payload
    - engineio.server
    - engineio.socket
    - engineio.async_drivers
  requires:
    - pip
    - pytest
    - aiohttp
    - tornado
    - websocket-client
    - requests
    - pytest-tornasync
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v -k "not ({{ skip_tests }})" tests

about:
  home: https://github.com/miguelgrinberg/python-engineio
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Engine.IO server

  summary: Adds caching support to your Flask application
  description: A fork of the Flask-cache extension which adds easy cache support to Flask.

  doc_url: https://python-engineio.readthedocs.io
  dev_url: https://github.com/miguelgrinberg/python-engineio

extra:
  recipe-maintainers:
    - pmlandwehr
    - ReimarBauer
    - synapticarbors