travis:
  secure:
    BINSTAR_TOKEN: T4pXZsTdTdM/tLDNtdEjr3utUFcTqz5Nc5WnHxw23kqBXuTSZwH+gZAKn2Be2sW3uBM9xsjKvsFbZBpsxOiaj/fTzF6q5mFhMj/LAKft3HRQl425tmd639z62LRWE6uy3RZuTB9oWT19g9OLwfRz54BvBrc3ifUZjM04usWUl9DtF2T1CMzIgIWSi8C03TR9WN6VQfeqYOCRSIUaSf6x3Ql/nH5Q/qiaNHXwwNoAHWZNHo7JfkdhQXEV2aB7XH/Fu/6m77o5YYPWb7Tvp6E035SjK28joJ3+L6dq+98ABfPLAGoFYjOJ2Ks65IVtPLj0Af16R+AyDnOU7WpTFSrNjk3a3HP+3OSTypSFxT4Ii2jyuzqM9xA0zyP2KgzvaDQ+Y6LXjc5raHwXG7//DEUBoobdtqx9pp5KuxDtvJh2SB/bqHOhNljGmvVEbuwCBTghgWPd8dUihj5ExBQYsEmyrYIumRD7+zQsWKLU89FPVqshYPgAoGqs9HbxozJ8AXGUWqTr57O/Nw1H92AnfIhpgTbyY+MF2NtCZGuOgYt1tZoA5GeiJZ6CjKjJq2iDLWneEFAbFuwPtSC4Rw0FYtLofbKfIa4q189tQZgO/DyWiQ4nYFRnMVgWkYvULZJ/ppWODvfsp89iyFW93vi05pBdzpN6N1mALrG2eRxGtEEVj0U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
