travis:
  secure:
    BINSTAR_TOKEN: bo+z2NojQcyo/x9hSY1rh2KjIlw2UUGdwtCSdxMWoNzWu7PQg75KVCcoGNYVXz8enHjG98BtqwfhE5VvvQTeAfRJ71iOpclIYEJ3ctuaYEvjbXKaiaDor02KOtExwnBTLuwDVDk5NBJTbpJSCsDif6Fi8+l3NZUG3vcXFWh9BepnRoHLPj+XMBnyIuHdeyFrmzEIG3vjM7fmUsc8/284vj+onhYcRKt3lhPCyeg2v3DyWKtf1hDF8VY9ZKvQLnDSOqkEyPHcTkjP3D+ThDEciqn7butSK8Z4uzENT5l1LYo4UJL0/QTtKCA82aB3LRmGdZG6kPSZpxnFflQsBru17QkubP9qPLhSnkHeSegOIio65bavJYVZI+VIDhw2qnI45zyqs7T55J906pVjXJFjUphyW/e3j8WcNspO3BdILyKmsAkB+JGS9AIWOo1Fy1sUE9rbVYgdLl+Z2sC9f6eYlRhC8SrDzBMv2uTcXcQqGhMdf+v1sPgMnlGSZ2TwbGOJlTJO84G6lurDMujYeKRnEKcckLgC7HSJfFUPM2Lzyvr4QedYPgtMMOpCmcu3hKTTkw/FtSzA5cTAvJE9+zl5mpAbYWEkG4i8lQxmSbctkXMmf8M4YikagqEp0QShWW6PMmzX2Btm0QQPNKcHkIHXJadHfL3s7oU6j58KdPbFGFw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
